name: HackGPT CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nmap nikto gobuster
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 hackgpt.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 hackgpt.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run installation test
      run: |
        python test_installation.py
    
    - name: Test import
      run: |
        python -c "from hackgpt import HackGPT, AIEngine, ToolManager; print('Import successful')"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security scan with bandit
      run: |
        pip install bandit
        bandit -r hackgpt.py -f json -o bandit-report.json || true
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-scan
        path: bandit-report.json

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t hackgpt:test .
    
    - name: Test Docker image
      run: |
        docker run --rm hackgpt:test --help
